# base
FROM node:24-alpine AS base
WORKDIR /app
COPY package.json yarn.lock ./

# deps
FROM base AS deps 
RUN yarn install --frozen-lockfile

# prod build
FROM deps AS builder 
COPY . .
RUN yarn build

# dev
FROM deps AS dev
COPY . . 
EXPOSE 3000
CMD ["yarn", "dev"] 

# prod
FROM node:24-alpine AS runner 
WORKDIR /app
COPY --from=builder /app/.next .next
COPY --from=builder /app/public public
COPY --from=builder /app/package.json package.json
COPY --from=builder /app/node_modules node_modules
EXPOSE 3000
CMD ["yarn", "start"]