# base
FROM golang:1.24-alpine AS base
WORKDIR /app
COPY go.mod go.sum ./

# deps
FROM base AS deps 
RUN go mod download

# prod build
FROM deps AS builder 
COPY . .
RUN go build -o server-app ./cmd/app

# dev
FROM deps AS dev 
COPY . .
EXPOSE 8080
CMD ["go", "run", "./cmd/app"]

# prod
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/server-app .
EXPOSE 8080
CMD ["./server-app"]