# base
FROM golang:1.24-alpine AS base
WORKDIR /app
COPY go.mod go.sum ./

# deps
FROM base AS deps 
RUN go mod download

# prod build
FROM deps AS builder 
COPY . .
RUN go build -o server-app ./cmd/app

# dev
FROM deps AS dev 
RUN go install github.com/air-verse/air@1.62.0
COPY . .
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]

# prod
FROM alpine:latest AS runner
WORKDIR /app
COPY --from=builder /app/server-app .
EXPOSE 8080
CMD ["./server-app"]